-- | Production cache-selection authority.  Candidate discovery, raw paths,
-- lifecycle fault injection, and test hooks remain in the hidden internal
-- module so callers can only consume closed facts or a scoped lease cascade.
module Adrai.Compiler.CacheSelection
  ( ExactArchiveCompileFacts (..),
    ExactArchiveAliasStatus (..),
    AncestorRank (..),
    CacheSelectionKind (..),
    CacheSelectionMetrics (..),
    CacheLeaseReuseFacts (..),
    CacheSelectionCascadeDecision (..),
    validateCacheContract,
    validateCachePublicationContract,
    validateCachePublicationConnection,
    validateExactCacheTarget,
    validateExactCacheTargetConnection,
    ValidatedCacheRows,
    withValidatedExactCacheTargetConnection,
    validatedRepositoryConfigRows,
    validatedManagedSourceRows,
    validatedOperationRows,
    validatedMemberRows,
    validatedCoverageRows,
    validatedOperationCommitRows,
    validatedLandingRows,
    validatedTargetRows,
    validatedLineConfigRows,
    validatedSearchMaterialization,
    readExactArchiveAliasStatus,
    withExactArchiveAliasRepair,
    exactArchiveAliasCompileFacts,
    refreshCacheMaterializationFingerprint,
    exactCacheArchivePath,
    treeIdenticalCheck,
    boundedHistoryIrrelevantCheck,
    boundedHistoryIrrelevantCount,
    withCacheSelectionCascade,
    semanticReuseScore,
  )
where

import Adrai.Compiler.CacheSelection.Internal
